apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # 1. Prometheus 자기 자신
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # 2. [추가] 외부 서버 OS 지표 (Node Exporter)
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['10.5.1.20:9100']
            labels:
              instance: 'proxy-server'
          - targets: ['10.5.4.90:9100']
            labels:
              instance: 'mysql-primary'
        relabel_configs:
          - target_label: job
            replacement: 'node-exporter'

      # 3. 백엔드 API (K8s Pods)
      - job_name: 'backend-api'
        metrics_path: '/metrics'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_label_component]
            separator: ;
            regex: backend;api
            action: keep
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: $1:3000
            target_label: __address__
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name
          - target_label: job
            replacement: backend-api

      # 4. 외부 MySQL 서비스
      - job_name: 'mysql-db'
        static_configs:
          - targets: ['10.5.4.90:9104']
        relabel_configs:
          - target_label: job
            replacement: mysql-master
          - target_label: instance
            replacement: 'mysql-primary'

      # 5. 외부 Nginx & HAProxy 서비스
      - job_name: 'external-proxy'
        static_configs:
          - targets: ['10.5.1.20:9113']
            labels:
              component: 'nginx'
          - targets: ['10.5.1.20:9101']
            labels:
              component: 'haproxy'
        relabel_configs:
          - target_label: instance
            replacement: 'proxy-server'

      # 6. K8s Pods 자동 탐지
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: replace
            target_label: job