apiVersion: v1
kind: Service
metadata:
  name: prometheus  # 이 이름이 나중에 Grafana 주소가 됩니다 (http://prometheus:9090)
  namespace: monitoring
spec:
  selector:
    app: prometheus  # prometheus-deployment.yaml의 label과 반드시 같아야 함
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP