{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  labels:
    {{- include "backend.commonLabels" . | nindent 4 }}
    component: {{ .Values.components.encoder }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "backend.commonLabels" . | nindent 12 }}
            component: {{ .Values.components.encoder }}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}

          containers:
            - name: backend-encoder
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}

              envFrom:
                - secretRef:
                    name: {{ .Values.secrets.name }}

              volumeMounts:
                - name: video-data
                  mountPath: {{ .Values.nfs.mountPath }}

          volumes:
            - name: video-data
              nfs:
                server: {{ .Values.nfs.server }}
                path: {{ .Values.nfs.path }}
{{- end }}
