{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  labels:
    {{- include "backend.commonLabels" . | nindent 4 }}
    component: {{ .Values.components.encoder }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "backend.commonLabels" . | nindent 8 }}
        component: {{ .Values.components.encoder }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
        - name: backend-encoder
          image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}

          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}

          volumeMounts:
            - name: video-data
              mountPath: {{ .Values.nfs.mountPath }}

      volumes:
        - name: video-data
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
{{- end }}
