{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
        - name: backend-encoder
          image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}
          volumeMounts:
            - name: video-data
              mountPath: {{ .Values.storage.mountPath }}
      volumes:
        - name: video-data
          persistentVolumeClaim:
            claimName: {{ .Values.storage.pvc.name }}
{{- end }}
