{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  labels:
    {{- include "backend.commonLabels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "backend.commonLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}

          containers:
            - name: backend-encoder
              image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}

              envFrom:
                - secretRef:
                    name: {{ .Values.secrets.name }}

              volumeMounts:
                - name: video-data
                  mountPath: {{ .Values.cronjob.nfs.mountPath }}

          volumes:
            - name: video-data
              nfs:
                server: {{ .Values.cronjob.nfs.server }}
                path: {{ .Values.cronjob.nfs.path }}
{{- end }}
