---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  capacity:
    storage: 9Gi  # 용량은 상황에 맞게 조절하세요.
  accessModes:
    - ReadWriteMany  # 여러 노드에서 동시에 읽고 쓰기 가능
  persistentVolumeReclaimPolicy: Retain # PVC 삭제 시 데이터 보존
  nfs:
    path: /mnt/loki  # [수정 필요] 외부 NFS 서버의 공유 디렉토리 경로
    server: 10.5.4.110 # [수정 필요] 외부 NFS 서버의 IP 주소
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 9Gi
  volumeName: loki-pv  