apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-db-5
  namespace: {{ .Release.Namespace }}
data:
  # 'dashboards/db-4.json'은 차트 루트 기준 경로입니다.
  main-dashboard.json: |-
{{ .Files.Get "dashboards/db-5.json" | indent 4 }}
